language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t noreallyimfine/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true noreallyimfine/docker-react npm run test

