sudo: required
services:
    - docker

before_install:
    - docker build -t noreallyimfine/docker-react -f Dockerfile.dev .

script:
    - docker run noreallyimfine/docker-react npm run test -- --coverage

